rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('search/', views.search, name='search'),   #mapping page search url
    path('register/', views.register, name='register'), 
    path('register/register_official/', views.register_official, name='register_official'), 
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('myaccount/', views.myaccount, name='myaccount'),
    path('myaccount/<str:data>/delete/', views.delete, name='delete'),
    path('allpages/', views.allpages, name='allpages'),
    path('allpages/<str:title>/likepage/', views.like_page, name='like_page'),
    path('allpages/searchnewsandpages/', views.searchnewsandpages, name='searchnewsandpages'),   #mapping news search url
    path('category/', views.category, name='category'),
    path('category/searchcategory/', views.searchcategory, name='searchcategory'),   #mapping categoroy search url
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('category/<slug:category_name_slug>/add_news/', views.add_news, name='add_news'),
    path('category/<str:category_name_slug>/<str:title>/comment/', views.show_comment, name='show_comment'),
    path('category/<str:category_name_slug>/<str:title>/news/', views.show_news, name='show_news'),
    path('category/<str:category_name_slug>/<str:title>/add_comment/', views.add_comment, name='add_comment'),
    

]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),  #allauth is an app, need to have a url

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
    
    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField(unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)


    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    def pic_url(self):
        if self.picture and hasattr(self.picture, 'url'):
            return self.picture.url
        else:
            return '/media/default_user.jpg'

    def __str__(self):
        return self.user.username


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    #page = models.ForeignKey(Page, on_delete=models.CASCADE)
    page = models.CharField(max_length=256)
    news = models.CharField(max_length=256)
    content = models.CharField(max_length=256)

    def __str__(self):
        return self.user.username

class News(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=512)
    title = models.CharField(max_length=32)
    content = models.CharField(max_length=512)

    def __str__(self):
        return self.title

class Likepage(models.Model): 
    user = models.ForeignKey(User,on_delete=models.CASCADE) 
    page = models.ForeignKey(Page,on_delete=models.CASCADE)
    likepageid = models.IntegerField(null=True)


    def __str__(self): 
        return self.page.title + "(liked by " + self.user.username + ")" 

rango/forms.py
from django import forms
from rango.models import News, Comment, Page, Category
from django.contrib.auth.models import User
from rango.models import UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name:")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    
    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
    help_text="Please enter the title of the page:")
    url = forms.URLField(max_length=200,
    help_text="Please enter the URL of the page:")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    class Meta:
        model = Page
        exclude = ('category',)
        
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)

class CommentForm(forms.ModelForm):
    content = forms.CharField( 
        help_text="Please enter the comment:",
        max_length=256,
    )
  
    #views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    class Meta:
        model = Comment
        fields = ('content',)
        #exclude = ('category',)
    
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        return cleaned_data

class NewsForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
    help_text="Please enter the title of the news:")
    content = forms.CharField(max_length=512,
    help_text="Please enter the content of the news:")
    
    #views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    class Meta:
        model = News
        exclude = ('user','category')
    
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        return cleaned_data

rango/views.py
from django.contrib.auth.models import Permission
from django.db.models.fields import NullBooleanField
from django.db.models.fields.related_descriptors import create_reverse_many_to_one_manager
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category, Page, Comment, News, UserProfile, Likepage
from rango.forms import CategoryForm
from django.shortcuts import redirect
from rango.forms import PageForm
from django.urls import reverse
from rango.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime
from rango.forms import CommentForm
from rango.forms import NewsForm


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    
    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list
    context_dict['ct1'] = category_list[0]
    context_dict['ct2'] = category_list[1]
    context_dict['ct3'] = category_list[2]

    visitor_cookie_handler(request)
    
    response = render(request, 'rango/index.html', context=context_dict)
    return response

def about(request):
    context_dict = {'boldmessage': 'This tutorial has been put together by Cheng Ye'}
    if request.session.test_cookie_worked():
        print("TEST COOKIE WORKED!")
        request.session.delete_test_cookie()
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    return render(request, 'rango/about.html', context=context_dict)

def category(request):
    context_dict = {}
    category_list_like = Category.objects.order_by('-likes')
    category_list_views = Category.objects.order_by('-views')
    page_list = Page.objects.order_by('-views')

    context_dict['category_all_views'] = category_list_views
    context_dict['pages'] = page_list

    return render(request, 'rango/all_category.html', context=context_dict)
    
def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        news = News.objects.filter(category=category.name)
        context_dict['pages'] = pages
        context_dict['category'] = category
        context_dict['news'] = news
    
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
        context_dict['news'] = None
    return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect('/rango/')
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    
    if category is None:
        return redirect('/rango/')
    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.likes = 0
                page.save()
                return redirect(reverse('rango:show_category',
                                         kwargs={'category_name_slug':category_name_slug}))
        else:
            print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

def allpages(request):
    context_dict = {}
    page_list = Page.objects.order_by('-views')
    news_list = News.objects.order_by('id')
    likepage_list = Likepage.objects.order_by('id')

    context_dict['pages'] = page_list
    context_dict['news'] = news_list
    context_dict['likepages'] = likepage_list
    context_dict['user'] = request.user

    return render(request, 'rango/all_pages.html', context=context_dict)


def register(request):
    registered = False
    
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request,'rango/register.html', context = {'user_form': user_form,
                  'profile_form': profile_form, 'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'rango/login.html')

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')
    
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    request.session['visits'] = visits

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

@login_required
def add_news(request, category_name_slug):
    if request.user.has_perm('rango.add_news')==False:
        return redirect('/rango/')
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    
    if category is None:
        return redirect('/rango/')
    form = NewsForm()

    if request.method == 'POST':
        form = NewsForm(request.POST)
        
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category.name
                page.user = request.user
                page.save()
                return redirect(reverse('rango:show_category',
                                         kwargs={'category_name_slug':category_name_slug}))
        else:
            print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_news.html', context=context_dict)

def show_comment(request, category_name_slug, title):
    context_dict = {}
    try:
        category = Category.objects.get(name=category_name_slug)
        page = Page.objects.get(title=title)    
        comments = Comment.objects.filter(page=page.title)
        context_dict['page'] = page
        context_dict['comments'] = comments
        context_dict['category'] = category
    
    except Page.DoesNotExist:
        page = News.objects.get(title=title)
        comments = Comment.objects.filter(news=page.title)
        context_dict['page'] = page
        context_dict['comments'] = comments
        context_dict['category'] = category
        
    return render(request, 'rango/comment.html', context=context_dict)

@login_required
def add_comment(request, category_name_slug, title):
    try:
        category = Category.objects.get(name=category_name_slug)
        page = Page.objects.get(title=title)
        count = 0
            
    except Page.DoesNotExist:
        page = News.objects.get(title=title)
        count = 1
    
    if page is None:
        return redirect('/rango/')

    form = CommentForm()    
    if request.method == 'POST':
        form = CommentForm(request.POST)      
        if form.is_valid():
            if page:
                comment = form.save(commit=False)
                if count == 0:
                    comment.page = page.title
                else :
                    comment.news = page.title
                comment.user = request.user
                comment.save()
                return redirect(reverse('rango:show_comment',
                                         kwargs={'category_name_slug':category_name_slug, 'title': title}))
        else:
            print(form.errors)
    context_dict = {'form': form, 'category': category, 'page':page}
    return render(request, 'rango/add_comment.html', context=context_dict)

def show_news(request, category_name_slug, title):

templates/rango/add_comment.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Add a comment
{% endblock %}
    
{% block body_block %}
</br> </br> </br> </br>
<!-- A form to collect comment inofrmation -->

        <h1>Add a comment to {{page.title}}</h1>
        <div>
            <form id="add_comment_form" method="post" action="/rango/category/{{ category.name }}/{{ page.title }}/add_comment/">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <input type="submit" name="submit" value="Add comment" />
            </form>
{% endblock %}

templates/rango/all_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
 
{% block title_block %}
All Categories
{% endblock %}
<!-- the page to show all the categories -->

{% block body_block %}


<div>
 <br/> <br/> <br/> <br/> <br/> <br/>
   
{% if category_all_views %}
 <!-- A table to show all the callegoies -->

<table class="all_cate_table" id="all_cate_table">
    {% for cate in category_all_views %}
    <tr style="border-bottom: 2px solid;  border-bottom: rgb(233, 122, 122);">
        <td style="text-align: center;">
            <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Category image" width="120" height="120">
            <h4><a href="{% url 'rango:show_category' cate.slug %}">{{ cate.name }}</a></h4>
        </td>
        <td>
         <!-- description is hard coded due to the lack of time -->
            <p>Descriptions: xxxxxx xxxxxxxxx xxxxx xxxxxxx xxxx xxxxxxxxx xxxxxxxx xxxxxxxx xxxxxx xxxxx</p>
            <a>Views: {{ cate.views }}  </a></br>
            <a>Likes: {{ cate.likes }} </a>
        </td>
        <td>
            {% if pages %}
         <!-- link to view all tyhe news and pages in this category  -->
            <h4><a href="{% url 'rango:show_category' cate.slug %}" style="font-size:12px">View all content in this category</a></h4>
            <table class="altrowstable" id="alternatecolor" style="font-size:12px; margin-left: 0px;">
                <tr>
                    <th>Title</th><th>URL</th><th>Views</th><th>Likes</th>
                </tr>
                {% for page in pages %}
                    {% if page.category == cate %}
                    <tr>
                        <td>{{ page.title }}</a></td>
                        <td><a href="{{ page.url }}">{{ page.url }}</a></td>
                        <td>{{ page.views }}</td>
                        <td>{{ page.likes }}</td>
                    </tr>
                    {% endif %}
            {% endfor %}
            </table>

            {% else %}
                <strong>There are no Links present.</strong>
            {% endif %}
        </td>
    </tr>
    {% endfor %}

{% else %}
    <strong>There are no categories present.</strong>
{% endif %}

</div>





<div>
    <p class="white_header">CATEGORIES</p>

    <!-- <div class="search_trans">
        <form>
            <input class="search_placeholder" type="text" placeholder="   Search for categories">
        </form>
    </div> -->

    <!--search categories-->
    <form class="form-inline mt-2 mt-md-0" role="search" method="get" id='searchform' action="{% url 'rango:searchcategory' %}">
        <input class="form-control mr-sm-2 search_trans" type="search" name='c' placeholder="Search categories" aria-label="Search" required>
        <button id=page_search_cate class="btn btn-outline-success my-2 my-sm-0 my_search2" type="submit">Search</button>
    </form>
</div>

<div>
    <p><a id="addCateGo" class="btn btn-secondary my_viewall" href="{% url 'rango:add_category' %}" role="button" style="position:absolute; top: 595px; left : 330px">Add a Category Here &raquo;</a></p>
    <br/>
    <select name="rank" style="top: 600px; right : 200px">
        <option>By views</option>
        <option>By likes</option>
        <option>Latest</option>
    </select>
    <select name="filter" style="top: 600px; left : 160px">
        <option>All categories</option>
        <option>My likes</option>
        <option>My contribution</option>
    </select>
</div>


{% endblock %}

templates/rango/all_pages.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
 
{% block title_block %}
All Pages
{% endblock %}

{% block body_block %}
<div>
    <p class="white_header">PAGES and News</p>

    <!-- search box on pages and news -->
    <form class="form-inline mt-2 mt-md-0" role="search" method="get" id='searchform' action="{% url 'rango:searchnewsandpages' %}">
        <input class="form-control mr-sm-2 search_trans" type="search" name = 'n' placeholder="Search for pages and news" aria-label="Search" required>
        <button id=page_search class="btn btn-outline-success my-2 my-sm-0 my_search2" type="submit">Search</button>
    </form>
</div>

<div>
 <!-- sorting buttons -->
    <p><a id="find_cate" class="btn btn-secondary my_viewall" href="{% url 'rango:category' %}" role="button" style="position:absolute; top: 595px; left : 330px">Find a category to add your centent &raquo;</a></p>
    <br/>
    <select name="rank" style="top: 600px; right : 200px">
        <option>By views</option>
        <option>By likes</option>
        <option>Latest</option>
    </select>
    <select name="filter" style="top: 600px; left : 160px">
        <option>All pages</option>
        <option>My likes</option>
        <option>My contribution</option>
    </select>
</div>



<br/> <br/> <br/> <br/> <br/> <br/>
<div>
 <!-- A table to list all the pages -->
{% if pages %}
<h2 style="text-align: center;">Pages</h2>

    <table class="altrowstable" id="all_page_table">
        {% for page in pages %}
        <tr style="padding-top: 10px;padding-bottom: 10px;">
            <td nowrap="nowrap">
                <a href="{{ page.url }}" style="font-style: oblique;font-weight: bold;color: rgb(90, 90, 90);">{{ page.title }}</a>
                <a href="/rango/category/{{ page.category.name }}/{{ page.title }}/comment/"><input type="image" src="/static/images/comment_icon.png"  width="20" height="20" alt="comment_icon" style="float: right;"/></a>
                </br>
                <a>Views: {{ page.views }} </a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                <a href="{% url 'rango:show_category' page.category.slug %}" style="color: rgb(90, 90, 90);text-decoration: underline;">Category: {{ page.category.name }} </a></br>

                <a>Likes: {{ page.likes }} </a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
       <!-- like fucntion implement -->
            {% if likepages %}
                {% for likepage in likepages %}
                    {% if likepage.user == user %}
                        {% if likepage.page == page %}
                            <a href="/rango/allpages/{{ page.title }}/likepage/"><input type="image" src="/static/images/like_icon.png"  width="20" height="20" alt="like_icon"/></a>
                        {% else %}
                            <a href="/rango/allpages/{{ page.title }}/likepage/"><input type="image" src="/static/images/unlike_icon.png"  width="20" height="20" alt="unlike_icon"/></a>
                        {% endif %}
                    {% else %}
                        <a href="/rango/allpages/{{ page }}/likepage/"><input type="image" src="/static/images/unlike_icon.png"  width="20" height="20" alt="unlike_icon"/></a>
                    {% endif%}
                {% endfor %}
            {% else %}
            <a href="/rango/allpages/{{ page }}/likepage/"><input type="image" src="/static/images/unlike_icon.png"  width="20" height="20" alt="unlike_icon"/></a>
            {% endif %}

            </td>

            <td style="padding-left: 20px;">
                <a>Descriptions: xxxxxx xxxxxxxxx xxxxx xxxxxxx xxxx xxxxxxxxx xxxxxxxx xxxxxxxx xxxxxx xxxxx</a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <strong>There are no pages represent.</strong>
{% endif %}


</br></br></br>

 <!-- A table to list all the news -->
{% if news %}
<h2 style="text-align: center;">News</h2>

<table class="altrowstable" id="all_page_table">
    {% for page in news %}
    <tr style="padding-top: 10px;padding-bottom: 10px;">
        <td nowrap="nowrap">
            <a href="/rango/category/{{ category.slug }}/{{ page.title }}/news/" style="font-style: oblique;font-weight: bold;color: rgb(90, 90, 90);">{{ page.title }}</a>
            <a href="/rango/category/{{ category.name }}/{{ page.title }}/comment/"><input type="image" src="/static/images/comment_icon.png"  width="20" height="20" alt="comment_icon" style="float: right;"/></a>
            </br>
            <a>Author: {{ page.user.username }} </a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
            <a href="#" style="color: rgb(90, 90, 90);text-decoration: underline;">Category: {{ page.category }} </a></br>
        </td>

        <td style="padding-left: 20px;">
            <a>Content: {{page.content}}</a>
        </td>
    </tr>
    {% endfor %}
</table>
{% else %}
    <strong>No news currently in category.</strong>
{% endif %}



</div>






{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="https://getbootstrap.com/docs/4.0/assets/img/favicons/favicon.ico">
    
        <title>
            {% block title_block %}
            {% endblock %}
        </title>
    
        <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/carousel/">
    
        <!-- Bootstrap core CSS -->
        <link href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" rel="stylesheet">
    
        <link href="https://getbootstrap.com/docs/4.0/examples/carousel/carousel.css" rel="stylesheet">
        <link href="/static/css/style.css" rel="stylesheet">
        <script src="/static/js/function.js"></script>

    
    </head>

    <body>

        <header>
            <!-- navigation bar -->
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark my_nav">
              <a class="navbar-brand" href="#">Rango Olympic</a>
              <!-- buttons on navigation bar -->
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'rango:index' %}">Home</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'rango:about' %}">About</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'rango:category' %}">Categories</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'rango:allpages' %}">Pages and News</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Discover</a>
                  </li>
                </ul>

                {% if user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'rango:myaccount' %}">My Account</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'rango:logout' %}">Logout</a>
                    </li>
                </ul>
                {% else %}
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'rango:login' %}">Login</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'rango:register' %}">Signup</a>
                    </li>
                </ul>
                {% endif %}

                <!-- search box on navigation bar -->
                <form class="form-inline mt-2 mt-md-0" role="search" method="get" id='searchform' action="{% url 'rango:search' %}" >
                  <input class="form-control mr-sm-2" type="search" name="q"  placeholder="Search" aria-label="Search" required>
                  <button id="nav_search" class="btn btn-outline-success my-2 my-sm-0 my_search" type="submit">Search</button>
                </form>
              </div>
            </nav>
        </header>
      
        <main role="main">

        <div class="container marketing">
            <!-- Background image -->
            <div>
                <img class="back_pic" src="{% static 'images/mainPicCut.PNG' %}" alt="BackgroundPic">
            </div>
            <div>
                {% block body_block %}

                {% endblock %}
            </div>
        </div>

        <div>
            {% block sidebar_block %}
                <!-- {% get_category_list category %} -->
            {% endblock %}
        </div>


        <hr />



        <!-- Footer with a back to top function -->
        <footer class="container">
            <p class="float-right"><a href="#" style="color:rgb(233, 122, 122)"><strong>Back to top</strong></a></p>
        </footer>
        </main>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.0/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
        <script src="https://getbootstrap.com/docs/4.0/assets/js/vendor/popper.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.0/dist/js/bootstrap.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.0/assets/js/vendor/holder.min.js"></script>    

    </body>
</html>